### ISSUE TITLE
Ön-işleme: duraklar

### ISSUE THREAD

**Issue by banbar** [agtokty/hu-service#6]
Duraklar üzerinde iki ön-işleme adımı olmalı:
* Aynı yol üzerinde bulunan ve yakın duraklar tek bir durak gibi gösterilmeli.
* Yolun iki tarafında olan duraklar düşünüldüğünde, personel Beytepe'ye daha yakın olan durağı seçebilmeli.

**Comment by agtokty** [comment]
solved at #2
